# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /usr/src/app

# Install dependencies (including dev)
COPY package.json package-lock.json ./
RUN npm install

# Copy source and build
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /usr/src/app

# Install only production dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy built artifacts
COPY --from=builder /usr/src/app/build ./build

# Set environment variable placeholder
ENV FIGMA_ACCESS_TOKEN=""

# Start the server
CMD ["node", "build/index.js"]
